name: Bug Report
description: Report a bug (without using the app's bug report feature)
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

        **Tip:** For easier debugging, use the "Report a Bug" button in the app settings. It generates a detailed system report automatically.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to make sure this bug hasn't been reported
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open the app
        2. Go to '...'
        3. Click on '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: COSMIC Camera Version
      description: Which version are you using? (visible in Settings > About)
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: installation
    attributes:
      label: Installation Method
      description: How did you install COSMIC Camera?
      options:
        - Flatpak (Flathub)
        - Flatpak (built from source)
        - Native (built from source)
        - Other
    validations:
      required: true

  - type: input
    id: distro
    attributes:
      label: Linux Distribution
      description: Which distro and version are you using?
      placeholder: e.g., Fedora 41, Ubuntu 24.04, Pop!_OS 22.04
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or screen recordings about the problem
      placeholder: Any additional information...
    validations:
      required: false
